### PR TITLE
HRIS-40 [BE] Implement GET specific Time Entry functionality

### PR DESCRIPTION
**Pull request by NiloJr-sun**
## Issue Link

https://framgiaph.backlog.com/view/HRIS-40

## Definition of Done

- [x] User can fetch Time In/Time Out and Remarks data from the Time Entry Table

## Notes
- BE integration only

## Pre-condition
- Existing Time In/Time Out record inside the Times table
- in your terminal run ``` docker compose up --build ```
- access ``` http://localhost:5257/graphql/ ```
- Try this query:
```
query ($id: Int!) {
    timeById(id: $id) {
        timeHour
        remarks
    }
  }
```
- Variable is the Id of the Time query we want to get:
```
{
  "id": 1
}
```

## Expected Output
- It should return the TimeHour and Remark of the Entry
```
{
  "data": {
    "timeById": {
      "timeHour": "PT9H15M",
      "remarks": "First time in"
    }
  }
}
```

## Screenshots/Recordings
image

### CODE REVIEW

**Review by jsvelte — APPROVED** [review]
# Approved 💯

**Review by rogeliojohnoliverio — APPROVED** [review]
Approved 🙇

**Review by arden-dave — APPROVED** [review]
Approve 💯

**Review by abduljalilpalala — APPROVED** [review]
### Approved! ✔️

**Pull request merged**
