### PR TITLE
HRIS-168 [Markup] Create Modal for filing a request for OT or Offset

### PR DESCRIPTION
**Pull request by JohnRoyCabezas**
## Issue Link

[Backlog Link](https://framgiaph.backlog.com/view/HRIS-168)

## Definition of Done

- [x] ESL Teachers can file offset request through the modal

## Pre-condition

npm run dev
go to http://localhost:3000/my-daily-time-record
make sure current user's position is set to esl teacher or (5) in Table plus
click the actions button on the table
click the filed offset
click file request
the modal should pop up

## Expected Output

ESL Teachers can file offset request through the modal

## Screenshots/Recordings

Desktop view
image

Mobile view
image

### CODE REVIEW

**Review by jsvelte — CHANGES_REQUESTED** [review]
Please add border red on Team Leader React Select Field
image

**Review by jsvelte — APPROVED** [review]
# Approved 💯

**Comment by NiloJr-sun** [comment]
Approved! 🐐

**Review by abduljalilpalala — APPROVED** [review]
### Approved! ✅

**Pull request merged**
