### PR TITLE
[HRIS-437]-[Improvement] Add error message if the server is down / offline

### PR DESCRIPTION
**Pull request by Fontilllas**
## Issue Link

[Backlog Link](https://framgiaph.backlog.com/view/HRIS-437)

## Definition of Done

-Can now see an error message when trying to save a form if offline.

## Notes
-I did not add an error message in Employee Management since in the staging it does not exist.

## Pre-condition

Commands to run
-Run 'docker compose up db'
-Run 'npm run dev' in client folder
-Run 'dotnet run' in api folder

## Expected Output

-It should now display an error message if the server down/offline.

## Screenshots/Recordings

Bulk Overtime Offlline:
https://github.com/user-attachments/assets/507352e0-2bce-4a5e-bbd9-55d75963a819

Change Shift Request Offline:
https://github.com/user-attachments/assets/ec6d1d1a-1049-4749-92a5-c8479f9b6241

Edit DTR Offline:
https://github.com/user-attachments/assets/c40580e7-0072-49ef-b10f-15e2836a9e52

Edit Leave Offline:
https://github.com/user-attachments/assets/ee1986dd-0bc7-4cdd-bb9b-c24ef4c3750a

Edit Undertime Offline:
https://github.com/user-attachments/assets/004ca8cd-ce4f-4cf1-8c4b-eb2fa40a58e3

ESL Change Shift Offline:
https://github.com/user-attachments/assets/ea12bf63-b101-430a-866e-3ae0892f29ba

File Offset Offline:
https://github.com/user-attachments/assets/d567fca6-48b3-4195-8189-d95889bf5419

Leave Offline:
https://github.com/user-attachments/assets/2f6279e9-cfd6-4e5b-9c64-3109e2c9696f

Overtime Offline:
https://github.com/user-attachments/assets/6972336b-3da3-4f56-9aba-f38c69c6a50b

Undertime Offline:
https://github.com/user-attachments/assets/8f6e02cf-f344-4084-affb-973ae926c40a

### CODE REVIEW

**Comment by JohnlynDC** [comment]
> Encountered a different modal on the Edit Undertime function. Attached below is the display of my edit undertime modal.

image

For the forms which are;
1. Bulk Overtime Offline
2. Change Shift Request Offline
3. Edit DTR Offline
4. Edit Leave Offline
5. ESL Change Shift Offline
6. File Offset Offline
7. Leave Offline
8. Overtime Offline
9. Undertime Offline

These forms displays an error message if the server down/offline.
https://drive.google.com/drive/folders/1wDhTqcHSkhfb_c5ISqgkTaJhR5gUgmrc?usp=sharing

**Comment by JohnlynDC** [comment]
> Resolved the issue on the different modal encountered

**Review by JohnlynDC — APPROVED** [review]
Approved

All these forms displays an error message when the server is down/offline. Attached below are the results.

https://drive.google.com/drive/folders/1wDhTqcHSkhfb_c5ISqgkTaJhR5gUgmrc?usp=sharing

Comments: 2
Testing Time: 2hrs
Iterations: 0

**Review by jessrey-asterisk — APPROVED** [review]
Approved

Tested all and found no errors

Proof
https://drive.google.com/drive/folders/1Fxdrza5O1bseDbjPKz6hh_yhNyD38FjW?usp=sharing

**Pull request merged**
